runtime: go111

instance_class: F1
automatic_scaling:
  max_concurrent_requests: 80
  min_pending_latency: 250ms
  max_pending_latency: 500ms
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.9
  max_instances: 10
  min_instances: 0

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

includes:
  - env.yaml
