@baseUrl = http://localhost:8080/api
@secret = abc123

###

GET {{baseUrl}}/memcache?key=a&key=b&key=c
X-Secret: {{secret}}

###

POST {{baseUrl}}/memcache
Content-Type: application/json
X-Secret: {{secret}}

{
    "Items": [
        {"Key": "a", "Value": "YWFhYWFhYQ=="},
        {"Key": "b", "Value": "YWFhYWFhYQ=="}
    ]
}

###

DELETE {{baseUrl}}/memcache?key=a
X-Secret: {{secret}}

###

GET {{baseUrl}}/search/sampleindex?q=mister&Facets=auto
X-Secret: {{secret}}

###

PUT {{baseUrl}}/search/sampleindex
Content-Type: application/json
X-Secret: {{secret}}

{
    "Docs": [
        {"ID": "t1", "Fields": [
            {"Name": "hello", "Type": "atom", "Derived": true, "Value": "world"},
            {"Name": "date", "Type": "date", "Value": "1/2/2020"},
            {"Name": "total", "Value": 20.25},
            {"Name": "content", "Value": "mister cat"},
            {"Name": "desc", "Type": "html", "Value": "<strong>phone</strong> specs"},
            {"Name": "type", "Facet": true, "Value": "computer"},
            {"Name": "ram", "Facet": true, "Value": 12}
        ]},
        {"ID": "t2", "Fields": [
            {"Name": "hello", "Type": "atom", "Value": "earth"},
            {"Name": "date", "Type": "date", "Value": "1/3/2020"},
            {"Name": "total", "Value": 30},
            {"Name": "content", "Value": "mister mice"},
            {"Name": "desc", "Type": "html", "Value": "<strong>phone</strong> call"},
            {"Name": "type", "Facet": true, "Value": "mobile"},
            {"Name": "ram", "Facet": true, "Value": 4},
            {"Name": "loc", "Type": "geopoint", "Value": "10.1,-100.1"}
        ]},
        {"ID": "t3", "Fields": [
            {"Name": "hello", "Type": "atom", "Value": "mars"},
            {"Name": "date", "Type": "date", "Value": "1/5/2020"},
            {"Name": "total", "Value": 23.5},
            {"Name": "content", "Value": "mister dog"},
            {"Name": "desc", "Type": "html", "Value": "<strong>phone</strong> text"},
            {"Name": "type", "Facet": true, "Value": "mobile"},
            {"Name": "ram", "Facet": true, "Value": 1},
            {"Name": "loc", "Type": "geopoint", "Value": "20.5,90.12"}
        ]}
    ]
}

###

DELETE http://localhost:8080/api/search/sampleindex?id=t1&id=t2&id=t3
X-Secret: {{secret}}