@baseUrl = http://localhost:8080/api
@secret = abc123

###

GET {{baseUrl}}/memcache?key=a&key=b&key=c
X-Secret: {{secret}}

###

POST {{baseUrl}}/memcache
Content-Type: application/json
X-Secret: {{secret}}

{
    "Items": [
        {"Key": "a", "Value": "YWFhYWFhYQ=="},
        {"Key": "b", "Value": "YWFhYWFhYQ=="}
    ]
}

###

DELETE {{baseUrl}}/memcache?key=a&key=b
X-Secret: {{secret}}