name: Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
      - name: Add environment
        run: echo "${{ secrets.APP_ENV }}" | base64 --decode > env.yaml
      - name: Install AppEngineGo component
        run: gcloud components install app-engine-go -q
      - name: Deploy Code
        run: gcloud app deploy app.yaml --project=${{ secrets.PROJECT_ID }} --version=v${GITHUB_RUN_NUMBER} -q
